#pragma once

#include <glad/glad.h>
#include <GLFW/glfw3.h>
#include <glm/glm.hpp>
#include <gl2d/gl2d.h>
#include <DoubleBuffer/DoubleBuffer.hpp>
#include <iostream>
#include <memory>
#include <thread>
#include <atomic>
#include <vector>
#include <array>
#include <algorithm>
#include <cmath>
#include <condition_variable>
#include <mutex>
#include <chrono>
#include <string>
#include <cstdint>